'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("ds_rpt_InformHSE"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class ds_rpt_InformHSE
    Inherits Global.System.Data.DataSet
    
    Private table_02_T03NFORME_HSE_PROYECTOS As _02_T03NFORME_HSE_PROYECTOSDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("_02_T03NFORME_HSE_PROYECTOS")) Is Nothing) Then
                MyBase.Tables.Add(New _02_T03NFORME_HSE_PROYECTOSDataTable(ds.Tables("_02_T03NFORME_HSE_PROYECTOS")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0"),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property _02_T03NFORME_HSE_PROYECTOS() As _02_T03NFORME_HSE_PROYECTOSDataTable
        Get
            Return Me.table_02_T03NFORME_HSE_PROYECTOS
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0"),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As ds_rpt_InformHSE = CType(MyBase.Clone,ds_rpt_InformHSE)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXml(reader)
            If (Not (ds.Tables("_02_T03NFORME_HSE_PROYECTOS")) Is Nothing) Then
                MyBase.Tables.Add(New _02_T03NFORME_HSE_PROYECTOSDataTable(ds.Tables("_02_T03NFORME_HSE_PROYECTOS")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.table_02_T03NFORME_HSE_PROYECTOS = CType(MyBase.Tables("_02_T03NFORME_HSE_PROYECTOS"),_02_T03NFORME_HSE_PROYECTOSDataTable)
        If (initTable = true) Then
            If (Not (Me.table_02_T03NFORME_HSE_PROYECTOS) Is Nothing) Then
                Me.table_02_T03NFORME_HSE_PROYECTOS.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Private Sub InitClass()
        Me.DataSetName = "ds_rpt_InformHSE"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/ds_rpt_InformHSE.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.table_02_T03NFORME_HSE_PROYECTOS = New _02_T03NFORME_HSE_PROYECTOSDataTable()
        MyBase.Tables.Add(Me.table_02_T03NFORME_HSE_PROYECTOS)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Private Function ShouldSerialize_02_T03NFORME_HSE_PROYECTOS() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As ds_rpt_InformHSE = New ds_rpt_InformHSE()
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Public Delegate Sub _02_T03NFORME_HSE_PROYECTOSRowChangeEventHandler(ByVal sender As Object, ByVal e As _02_T03NFORME_HSE_PROYECTOSRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class _02_T03NFORME_HSE_PROYECTOSDataTable
        Inherits Global.System.Data.TypedTableBase(Of _02_T03NFORME_HSE_PROYECTOSRow)
        
        Private column_02_T03Id_ReporteCasos As Global.System.Data.DataColumn
        
        Private column_02_T03Id_Informe As Global.System.Data.DataColumn
        
        Private column_02_T03FechaRegistro As Global.System.Data.DataColumn
        
        Private column_02_T03usuarioRegistra As Global.System.Data.DataColumn
        
        Private column_02_T03NumCtoMarco As Global.System.Data.DataColumn
        
        Private column_02_T03Mes As Global.System.Data.DataColumn
        
        Private column_02_T03FechaSemana_Inicio As Global.System.Data.DataColumn
        
        Private column_02_T03FechaSemana_Final As Global.System.Data.DataColumn
        
        Private column_02_T03Depto As Global.System.Data.DataColumn
        
        Private column_02_T03Municipio As Global.System.Data.DataColumn
        
        Private column_02_T03ODS As Global.System.Data.DataColumn
        
        Private column_02_T03AreaCliente As Global.System.Data.DataColumn
        
        Private column_02_T03ActividadesEjecutadas As Global.System.Data.DataColumn
        
        Private column_02_T03Id_EstadisticaDiaria As Global.System.Data.DataColumn
        
        Private column_02_T03Id_Personal As Global.System.Data.DataColumn
        
        Private column_02_T03Id_SeguridadVial As Global.System.Data.DataColumn
        
        Private column_02_T03Id_RegistroFotografico As Global.System.Data.DataColumn
        
        Private column02_T03ResponsableInforme As Global.System.Data.DataColumn
        
        Private column_02_T03ComentariosFinales As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "_02_T03NFORME_HSE_PROYECTOS"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03Id_ReporteCasosColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03Id_ReporteCasos
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03Id_InformeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03Id_Informe
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03FechaRegistroColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03FechaRegistro
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03usuarioRegistraColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03usuarioRegistra
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03NumCtoMarcoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03NumCtoMarco
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03MesColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03Mes
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03FechaSemana_InicioColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03FechaSemana_Inicio
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03FechaSemana_FinalColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03FechaSemana_Final
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03DeptoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03Depto
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03MunicipioColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03Municipio
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03ODSColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03ODS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03AreaClienteColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03AreaCliente
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03ActividadesEjecutadasColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03ActividadesEjecutadas
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03Id_EstadisticaDiariaColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03Id_EstadisticaDiaria
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03Id_PersonalColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03Id_Personal
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03Id_SeguridadVialColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03Id_SeguridadVial
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03Id_RegistroFotograficoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03Id_RegistroFotografico
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03ResponsableInformeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column02_T03ResponsableInforme
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property _02_T03ComentariosFinalesColumn() As Global.System.Data.DataColumn
            Get
                Return Me.column_02_T03ComentariosFinales
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0"),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As _02_T03NFORME_HSE_PROYECTOSRow
            Get
                Return CType(Me.Rows(index),_02_T03NFORME_HSE_PROYECTOSRow)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Event _02_T03NFORME_HSE_PROYECTOSRowChanging As _02_T03NFORME_HSE_PROYECTOSRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Event _02_T03NFORME_HSE_PROYECTOSRowChanged As _02_T03NFORME_HSE_PROYECTOSRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Event _02_T03NFORME_HSE_PROYECTOSRowDeleting As _02_T03NFORME_HSE_PROYECTOSRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Event _02_T03NFORME_HSE_PROYECTOSRowDeleted As _02_T03NFORME_HSE_PROYECTOSRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Overloads Sub Add_02_T03NFORME_HSE_PROYECTOSRow(ByVal row As _02_T03NFORME_HSE_PROYECTOSRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Overloads Function Add_02_T03NFORME_HSE_PROYECTOSRow( _
                    ByVal _02_T03Id_ReporteCasos As String,  _
                    ByVal _02_T03Id_Informe As String,  _
                    ByVal _02_T03FechaRegistro As String,  _
                    ByVal _02_T03usuarioRegistra As String,  _
                    ByVal _02_T03NumCtoMarco As String,  _
                    ByVal _02_T03Mes As String,  _
                    ByVal _02_T03FechaSemana_Inicio As String,  _
                    ByVal _02_T03FechaSemana_Final As String,  _
                    ByVal _02_T03Depto As String,  _
                    ByVal _02_T03Municipio As String,  _
                    ByVal _02_T03ODS As String,  _
                    ByVal _02_T03AreaCliente As String,  _
                    ByVal _02_T03ActividadesEjecutadas As String,  _
                    ByVal _02_T03Id_EstadisticaDiaria As String,  _
                    ByVal _02_T03Id_Personal As String,  _
                    ByVal _02_T03Id_SeguridadVial As String,  _
                    ByVal _02_T03Id_RegistroFotografico As String,  _
                    ByVal _02_T03ResponsableInforme As String,  _
                    ByVal _02_T03ComentariosFinales As String) As _02_T03NFORME_HSE_PROYECTOSRow
            Dim row_02_T03NFORME_HSE_PROYECTOSRow As _02_T03NFORME_HSE_PROYECTOSRow = CType(Me.NewRow,_02_T03NFORME_HSE_PROYECTOSRow)
            Dim columnValuesArray() As Object = New Object() {_02_T03Id_ReporteCasos, _02_T03Id_Informe, _02_T03FechaRegistro, _02_T03usuarioRegistra, _02_T03NumCtoMarco, _02_T03Mes, _02_T03FechaSemana_Inicio, _02_T03FechaSemana_Final, _02_T03Depto, _02_T03Municipio, _02_T03ODS, _02_T03AreaCliente, _02_T03ActividadesEjecutadas, _02_T03Id_EstadisticaDiaria, _02_T03Id_Personal, _02_T03Id_SeguridadVial, _02_T03Id_RegistroFotografico, _02_T03ResponsableInforme, _02_T03ComentariosFinales}
            row_02_T03NFORME_HSE_PROYECTOSRow.ItemArray = columnValuesArray
            Me.Rows.Add(row_02_T03NFORME_HSE_PROYECTOSRow)
            Return row_02_T03NFORME_HSE_PROYECTOSRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As _02_T03NFORME_HSE_PROYECTOSDataTable = CType(MyBase.Clone,_02_T03NFORME_HSE_PROYECTOSDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New _02_T03NFORME_HSE_PROYECTOSDataTable()
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Friend Sub InitVars()
            Me.column_02_T03Id_ReporteCasos = MyBase.Columns("_02_T03Id_ReporteCasos")
            Me.column_02_T03Id_Informe = MyBase.Columns("_02_T03Id_Informe")
            Me.column_02_T03FechaRegistro = MyBase.Columns("_02_T03FechaRegistro")
            Me.column_02_T03usuarioRegistra = MyBase.Columns("_02_T03usuarioRegistra")
            Me.column_02_T03NumCtoMarco = MyBase.Columns("_02_T03NumCtoMarco")
            Me.column_02_T03Mes = MyBase.Columns("_02_T03Mes")
            Me.column_02_T03FechaSemana_Inicio = MyBase.Columns("_02_T03FechaSemana_Inicio")
            Me.column_02_T03FechaSemana_Final = MyBase.Columns("_02_T03FechaSemana_Final")
            Me.column_02_T03Depto = MyBase.Columns("_02_T03Depto")
            Me.column_02_T03Municipio = MyBase.Columns("_02_T03Municipio")
            Me.column_02_T03ODS = MyBase.Columns("_02_T03ODS")
            Me.column_02_T03AreaCliente = MyBase.Columns("_02_T03AreaCliente")
            Me.column_02_T03ActividadesEjecutadas = MyBase.Columns("_02_T03ActividadesEjecutadas")
            Me.column_02_T03Id_EstadisticaDiaria = MyBase.Columns("_02_T03Id_EstadisticaDiaria")
            Me.column_02_T03Id_Personal = MyBase.Columns("_02_T03Id_Personal")
            Me.column_02_T03Id_SeguridadVial = MyBase.Columns("_02_T03Id_SeguridadVial")
            Me.column_02_T03Id_RegistroFotografico = MyBase.Columns("_02_T03Id_RegistroFotografico")
            Me.column02_T03ResponsableInforme = MyBase.Columns("02_T03ResponsableInforme")
            Me.column_02_T03ComentariosFinales = MyBase.Columns("_02_T03ComentariosFinales")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Private Sub InitClass()
            Me.column_02_T03Id_ReporteCasos = New Global.System.Data.DataColumn("_02_T03Id_ReporteCasos", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03Id_ReporteCasos)
            Me.column_02_T03Id_Informe = New Global.System.Data.DataColumn("_02_T03Id_Informe", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03Id_Informe)
            Me.column_02_T03FechaRegistro = New Global.System.Data.DataColumn("_02_T03FechaRegistro", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03FechaRegistro)
            Me.column_02_T03usuarioRegistra = New Global.System.Data.DataColumn("_02_T03usuarioRegistra", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03usuarioRegistra)
            Me.column_02_T03NumCtoMarco = New Global.System.Data.DataColumn("_02_T03NumCtoMarco", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03NumCtoMarco)
            Me.column_02_T03Mes = New Global.System.Data.DataColumn("_02_T03Mes", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03Mes)
            Me.column_02_T03FechaSemana_Inicio = New Global.System.Data.DataColumn("_02_T03FechaSemana_Inicio", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03FechaSemana_Inicio)
            Me.column_02_T03FechaSemana_Final = New Global.System.Data.DataColumn("_02_T03FechaSemana_Final", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03FechaSemana_Final)
            Me.column_02_T03Depto = New Global.System.Data.DataColumn("_02_T03Depto", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03Depto)
            Me.column_02_T03Municipio = New Global.System.Data.DataColumn("_02_T03Municipio", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03Municipio)
            Me.column_02_T03ODS = New Global.System.Data.DataColumn("_02_T03ODS", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03ODS)
            Me.column_02_T03AreaCliente = New Global.System.Data.DataColumn("_02_T03AreaCliente", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03AreaCliente)
            Me.column_02_T03ActividadesEjecutadas = New Global.System.Data.DataColumn("_02_T03ActividadesEjecutadas", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03ActividadesEjecutadas)
            Me.column_02_T03Id_EstadisticaDiaria = New Global.System.Data.DataColumn("_02_T03Id_EstadisticaDiaria", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03Id_EstadisticaDiaria)
            Me.column_02_T03Id_Personal = New Global.System.Data.DataColumn("_02_T03Id_Personal", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03Id_Personal)
            Me.column_02_T03Id_SeguridadVial = New Global.System.Data.DataColumn("_02_T03Id_SeguridadVial", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03Id_SeguridadVial)
            Me.column_02_T03Id_RegistroFotografico = New Global.System.Data.DataColumn("_02_T03Id_RegistroFotografico", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03Id_RegistroFotografico)
            Me.column02_T03ResponsableInforme = New Global.System.Data.DataColumn("02_T03ResponsableInforme", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            Me.column02_T03ResponsableInforme.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "column02_T03ResponsableInforme")
            Me.column02_T03ResponsableInforme.ExtendedProperties.Add("Generator_UserColumnName", "02_T03ResponsableInforme")
            MyBase.Columns.Add(Me.column02_T03ResponsableInforme)
            Me.column_02_T03ComentariosFinales = New Global.System.Data.DataColumn("_02_T03ComentariosFinales", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.column_02_T03ComentariosFinales)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function New_02_T03NFORME_HSE_PROYECTOSRow() As _02_T03NFORME_HSE_PROYECTOSRow
            Return CType(Me.NewRow,_02_T03NFORME_HSE_PROYECTOSRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New _02_T03NFORME_HSE_PROYECTOSRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(_02_T03NFORME_HSE_PROYECTOSRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me._02_T03NFORME_HSE_PROYECTOSRowChangedEvent) Is Nothing) Then
                RaiseEvent _02_T03NFORME_HSE_PROYECTOSRowChanged(Me, New _02_T03NFORME_HSE_PROYECTOSRowChangeEvent(CType(e.Row,_02_T03NFORME_HSE_PROYECTOSRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me._02_T03NFORME_HSE_PROYECTOSRowChangingEvent) Is Nothing) Then
                RaiseEvent _02_T03NFORME_HSE_PROYECTOSRowChanging(Me, New _02_T03NFORME_HSE_PROYECTOSRowChangeEvent(CType(e.Row,_02_T03NFORME_HSE_PROYECTOSRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me._02_T03NFORME_HSE_PROYECTOSRowDeletedEvent) Is Nothing) Then
                RaiseEvent _02_T03NFORME_HSE_PROYECTOSRowDeleted(Me, New _02_T03NFORME_HSE_PROYECTOSRowChangeEvent(CType(e.Row,_02_T03NFORME_HSE_PROYECTOSRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me._02_T03NFORME_HSE_PROYECTOSRowDeletingEvent) Is Nothing) Then
                RaiseEvent _02_T03NFORME_HSE_PROYECTOSRowDeleting(Me, New _02_T03NFORME_HSE_PROYECTOSRowChangeEvent(CType(e.Row,_02_T03NFORME_HSE_PROYECTOSRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Remove_02_T03NFORME_HSE_PROYECTOSRow(ByVal row As _02_T03NFORME_HSE_PROYECTOSRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
            Dim ds As ds_rpt_InformHSE = New ds_rpt_InformHSE()
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "_02_T03NFORME_HSE_PROYECTOSDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    Partial Public Class _02_T03NFORME_HSE_PROYECTOSRow
        Inherits Global.System.Data.DataRow
        
        Private table_02_T03NFORME_HSE_PROYECTOS As _02_T03NFORME_HSE_PROYECTOSDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.table_02_T03NFORME_HSE_PROYECTOS = CType(Me.Table,_02_T03NFORME_HSE_PROYECTOSDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03Id_ReporteCasos() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_ReporteCasosColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03Id_ReporteCasos' de la tabla '_02_T03NFORME_HSE_PR"& _ 
                            "OYECTOS' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_ReporteCasosColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03Id_Informe() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_InformeColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03Id_Informe' de la tabla '_02_T03NFORME_HSE_PROYECT"& _ 
                            "OS' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_InformeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03FechaRegistro() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03FechaRegistroColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03FechaRegistro' de la tabla '_02_T03NFORME_HSE_PROY"& _ 
                            "ECTOS' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03FechaRegistroColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03usuarioRegistra() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03usuarioRegistraColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03usuarioRegistra' de la tabla '_02_T03NFORME_HSE_PR"& _ 
                            "OYECTOS' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03usuarioRegistraColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03NumCtoMarco() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03NumCtoMarcoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03NumCtoMarco' de la tabla '_02_T03NFORME_HSE_PROYEC"& _ 
                            "TOS' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03NumCtoMarcoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03Mes() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03MesColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03Mes' de la tabla '_02_T03NFORME_HSE_PROYECTOS' es "& _ 
                            "DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03MesColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03FechaSemana_Inicio() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03FechaSemana_InicioColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03FechaSemana_Inicio' de la tabla '_02_T03NFORME_HSE"& _ 
                            "_PROYECTOS' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03FechaSemana_InicioColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03FechaSemana_Final() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03FechaSemana_FinalColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03FechaSemana_Final' de la tabla '_02_T03NFORME_HSE_"& _ 
                            "PROYECTOS' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03FechaSemana_FinalColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03Depto() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03DeptoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03Depto' de la tabla '_02_T03NFORME_HSE_PROYECTOS' e"& _ 
                            "s DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03DeptoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03Municipio() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03MunicipioColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03Municipio' de la tabla '_02_T03NFORME_HSE_PROYECTO"& _ 
                            "S' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03MunicipioColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03ODS() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03ODSColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03ODS' de la tabla '_02_T03NFORME_HSE_PROYECTOS' es "& _ 
                            "DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03ODSColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03AreaCliente() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03AreaClienteColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03AreaCliente' de la tabla '_02_T03NFORME_HSE_PROYEC"& _ 
                            "TOS' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03AreaClienteColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03ActividadesEjecutadas() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03ActividadesEjecutadasColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03ActividadesEjecutadas' de la tabla '_02_T03NFORME_"& _ 
                            "HSE_PROYECTOS' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03ActividadesEjecutadasColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03Id_EstadisticaDiaria() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_EstadisticaDiariaColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03Id_EstadisticaDiaria' de la tabla '_02_T03NFORME_H"& _ 
                            "SE_PROYECTOS' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_EstadisticaDiariaColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03Id_Personal() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_PersonalColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03Id_Personal' de la tabla '_02_T03NFORME_HSE_PROYEC"& _ 
                            "TOS' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_PersonalColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03Id_SeguridadVial() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_SeguridadVialColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03Id_SeguridadVial' de la tabla '_02_T03NFORME_HSE_P"& _ 
                            "ROYECTOS' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_SeguridadVialColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03Id_RegistroFotografico() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_RegistroFotograficoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03Id_RegistroFotografico' de la tabla '_02_T03NFORME"& _ 
                            "_HSE_PROYECTOS' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_RegistroFotograficoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03ResponsableInforme() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03ResponsableInformeColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '02_T03ResponsableInforme' de la tabla '_02_T03NFORME_HSE_"& _ 
                            "PROYECTOS' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03ResponsableInformeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property _02_T03ComentariosFinales() As String
            Get
                Try 
                    Return CType(Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03ComentariosFinalesColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna '_02_T03ComentariosFinales' de la tabla '_02_T03NFORME_HSE"& _ 
                            "_PROYECTOS' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03ComentariosFinalesColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03Id_ReporteCasosNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_ReporteCasosColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03Id_ReporteCasosNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_ReporteCasosColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03Id_InformeNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_InformeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03Id_InformeNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_InformeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03FechaRegistroNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03FechaRegistroColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03FechaRegistroNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03FechaRegistroColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03usuarioRegistraNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03usuarioRegistraColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03usuarioRegistraNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03usuarioRegistraColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03NumCtoMarcoNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03NumCtoMarcoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03NumCtoMarcoNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03NumCtoMarcoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03MesNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03MesColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03MesNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03MesColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03FechaSemana_InicioNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03FechaSemana_InicioColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03FechaSemana_InicioNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03FechaSemana_InicioColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03FechaSemana_FinalNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03FechaSemana_FinalColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03FechaSemana_FinalNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03FechaSemana_FinalColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03DeptoNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03DeptoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03DeptoNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03DeptoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03MunicipioNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03MunicipioColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03MunicipioNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03MunicipioColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03ODSNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03ODSColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03ODSNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03ODSColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03AreaClienteNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03AreaClienteColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03AreaClienteNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03AreaClienteColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03ActividadesEjecutadasNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03ActividadesEjecutadasColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03ActividadesEjecutadasNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03ActividadesEjecutadasColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03Id_EstadisticaDiariaNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_EstadisticaDiariaColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03Id_EstadisticaDiariaNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_EstadisticaDiariaColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03Id_PersonalNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_PersonalColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03Id_PersonalNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_PersonalColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03Id_SeguridadVialNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_SeguridadVialColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03Id_SeguridadVialNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_SeguridadVialColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03Id_RegistroFotograficoNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_RegistroFotograficoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03Id_RegistroFotograficoNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03Id_RegistroFotograficoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03ResponsableInformeNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03ResponsableInformeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03ResponsableInformeNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03ResponsableInformeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function Is_02_T03ComentariosFinalesNull() As Boolean
            Return Me.IsNull(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03ComentariosFinalesColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub Set_02_T03ComentariosFinalesNull()
            Me(Me.table_02_T03NFORME_HSE_PROYECTOS._02_T03ComentariosFinalesColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Public Class _02_T03NFORME_HSE_PROYECTOSRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As _02_T03NFORME_HSE_PROYECTOSRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub New(ByVal row As _02_T03NFORME_HSE_PROYECTOSRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Row() As _02_T03NFORME_HSE_PROYECTOSRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
